name: Activity

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  chess:
    name: Activity update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cheesits456/github-activity-readme@16bd144b812ce901e0693fee5c36c02e75e6b4a7
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
