name: Activity

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  chess:
    name: Activity update
    runs-on: ubuntu-latest

    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      discussions: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
      - uses: actions/checkout@v3

      - uses: cheesits456/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
