name: Update Activity

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  chess:
    name: Update activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cheesits456/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}